### ISSUE TITLE
创建GitHub Action自动同步pyghmi代码

### ISSUE THREAD

**Issue by cceniam** [cceniam/pyghmi#1]
## 需求描述

创建一个GitHub Action工作流，用于自动将来自 https://opendev.org/x/pyghmi.git 的代码更新同步到当前项目中。

### 1. 创建工作流文件

创建 `.github/workflows/sync-pyghmi.yml` 文件，包含以下功能：

```yaml
name: Sync pyghmi from OpenDev

on:
  schedule:
    # 每天凌晨2点执行（UTC时间）
    - cron: '0 2 * * *'
  workflow_dispatch: # 允许手动触发
  
jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Add upstream remote
      run: |
        git remote add upstream https://opendev.org/x/pyghmi.git || true
        git fetch upstream
    
    - name: Sync with upstream
      run: |
        git checkout main
        git merge upstream/master --allow-unrelated-histories
    
    - name: Push changes
      run: |
        git push origin main
```

### 2. 配置选项

- **自动触发**: 每天凌晨2点（UTC）自动执行同步
- **手动触发**: 支持通过GitHub界面手动执行
- **冲突处理**: 使用 `--allow-unrelated-histories` 处理可能的历史冲突

### 3. 权限配置

确保Repository具有以下权限：
- Actions: Read and write
- Contents: Write
- Metadata: Read

### 4. 注意事项

1. **分支名称**: 假设本地使用 `main` 分支，上游使用 `master` 分支
2. **冲突解决**: 如果存在合并冲突，Action会失败，需要手动解决
3. **备份**: 建议在首次运行前创建分支备份

### 5. 可选增强功能

- 添加Slack/Email通知
- 创建Pull Request而非直接合并
- 添加代码质量检查
- 设置同步频率配置

## 验收标准

- [ ] GitHub Action文件创建完成
- [ ] 工作流可以手动触发成功
- [ ] 定时同步功能正常工作
- [ ] 同步过程中的错误能够被正确处理和报告
